version: '3.7'

networks:

  tor-ssb:
    driver: bridge

volumes:

  tor:
  ssb:

services:

  tor:
    hostname: tor
    container_name: tor
    build: tor/
    volumes:
      - tor:/var/lib/tor
    networks:
      - tor-ssb
    restart: always

  ssb:
    container_name: ssb
    hostname: ssb
    build: ssb/
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    volumes:
      - ssb:/root/.ssb
      - tor:/var/lib/tor
    networks:
      - tor-ssb
    restart: always
    depends_on:
      -  tor

