version: '3.7'

networks:

  tor-ssb:
    driver: bridge

volumes:

  tor:
  ssb-pub:

services:

  tor:
    hostname: tor
    container_name: tor
    build: tor/
    volumes:
      - tor:/var/lib/tor
    networks:
      - tor-ssb
    restart: always

  ssb-pub:
    container_name: ssb-pub
    hostname: ssb-pub
    build: ssb-pub/
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    volumes:
      - ssb-pub:/root/.ssb
      - tor:/var/lib/tor
    networks:
      - tor-ssb
    restart: always
    depends_on:
      -  tor

